name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build website
        run: nix develop --command -- make doc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy index.html to root
        run: cp ./target/aarch64-unknown-none-softfloat/doc/kernel/index.html ./target/aarch64-unknown-none-softfloat/doc/index.html

      - name: Add redirect (change later to /index.html when we move to subdomain)
        run: echo '<meta http-equiv="refresh" content="0;url=/sark/kernel/">' > target/aarch6 4-unknown-none-softfloat/doc/index.html

      - name: Remove lock file
        run: rm target/aarch64-unknown-none-softfloat/doc/.lock

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./target/aarch64-unknown-none-softfloat/doc"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
