name: Build & Release CI

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*


jobs:
  build-and-release:
    strategy:
      matrix:
        version: [rpi3, rpi4, rpi5]

    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build the kernel image
        run: nix build .#${{ matrix.version }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: |
            ./result/bin/kernel8_${{ matrix.version }}.img
